### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by benoitsteiner** [ProGTX/sycl-gtx#15]
I started by using the default compiler on my machine (gcc 4.8), however it doesn't support the -fdiagnostics-color option:
`
Scanning dependencies of target sycl-gtx
[  3%] Building CXX object sycl-gtx/CMakeFiles/sycl-gtx.dir/source/context.cpp.o
c++: error: unrecognized command line option ‘-fdiagnostics-color’
`
I then switched to clang 3.6, but I ended up with the following error:
`
sycl-gtx/sycl-gtx/include/CL/detail/debug.h:90:12: error: 
      call to deleted constructor of 'debug'
    return debug("SYCL warning: ", message);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sycl-gtx/sycl-gtx/include/CL/detail/debug.h:60:3: note: 
      'debug' has been explicitly marked deleted here
  debug(const debug& copy) = delete;
`
I then switched back to gcc, after to commenting out the offending option in color_diagnostics.cmake, but ended up with another instance of the deleted constructor error:
`
sycl-gtx/sycl-gtx/source/command_group.cpp: In member function ‘void cl::sycl::detail::command_group::flush(cl::sycl::vector_class<_cl_event*>)’:
sycl-gtx/sycl-gtx/source/command_group.cpp:102:22: error: use of deleted function ‘debug::debug(debug&&)’
       auto d = debug();
                      ^
In file included from sycl-gtx/sycl-gtx/include/CL/access.h:3:0,
                 from sycl-gtx/sycl-gtx/include/CL/command_group.h:5,
                 from sycl-gtx/sycl-gtx/source/command_group.cpp:1:
sycl-gtx/sycl-gtx/include/CL/detail/debug.h:58:3: note: ‘debug::debug(debug&&)’ is implicitly deleted because the default definition would be ill-formed:
   debug(debug&& move) = default;
`

**Comment by ProGTX** [comment]
Thank you, I shouldn't rely only on Visual Studio when pushing code :)

I'm working on this. There were many more issues than just this one. I've now made the color diagnostics opt-in (888a6662d9a5d8647a4273438b0ad40d925be57b), moved all files into the SYCL folder and fixed some include errors (f5440f0bc90c8b7042d63e2afd2f01382cf73839), and some minor fixes. This was enough to get the code fully compile and link on Linux using GCC 5.4 and Clang 3.8, but I get the same error as you when using GCC 4.8, so this still needs to be fixed.

**Comment by ProGTX** [comment]
It turns out GCC failed because of it's own bug - [no move constructor for stringstream](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54316). I've fixed that in 31616d144db8eff535acb90b2b2ae1b35e0f9bc4.

So now it also works for me with GCC 4.8.5, Clang 3.5.2, and Clang 3.6.2 (along with higher versions). But I was not able to replicate your bug with Clang, for me it worked even before this fix. I hope it'll work now.

**Comment by benoitsteiner** [comment]
Thanks. I can confirm that the code compile with gcc, and I managed to get the code to compile with clang 3.6 by making sure that NDEBUG is defined.

**Comment by ProGTX** [comment]
OK, thanks for the feedback. `NDEBUG` should be defined by CMake if you use `-DCMAKE_BUILD_TYPE=Release`, but I thought it worked even without that. Anyway, I'm marking this as closed and may investigate `NDEBUG` in a separate issue.
