### ISSUE TITLE
Can't install sycl-gtx  on ubuntu-14.04  with Nvidia implémentation of OpenCL

### ISSUE THREAD

**Issue by babouFomb** [ProGTX/sycl-gtx#16]
I try to install sycl-gtx, I read your Readme.md file, but in this file you don't provide any explanation about the installation steps.

I execute the following commands:
`mkdir build`
`cmake ..`
This is th output of cmake:
`rokiatou@rokiatou:~/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build$ cmake ..`
`-- The C compiler identification is GNU 4.8.4`  
`-- The CXX compiler identification is GNU 4.8.4`
`-- Check for working C compiler: /usr/bin/cc`
`-- Check for working C compiler: /usr/bin/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Check for working CXX compiler: /usr/bin/c++`
`-- Check for working CXX compiler: /usr/bin/c++ -- works`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- Try OpenMP C flag = [-fopenmp]`
`-- Performing Test OpenMP_FLAG_DETECTED`
`-- Performing Test OpenMP_FLAG_DETECTED - Success`
`-- Try OpenMP CXX flag = [-fopenmp]`
`-- Performing Test OpenMP_FLAG_DETECTED`
`-- Performing Test OpenMP_FLAG_DETECTED - Success`
`-- Found OpenMP: -fopenmp `
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build`

I can see, the commande 
`find_package(OpenCL REQUIRED)`
at line 11 of CMakelist.txt is not executed, so OpenCL was not located.
My OpenCL headers and libs are in `/usr/local/cuda/`
I have not any problem to compile and execute a OpenCL projects.

After running cmake, I run `make`, this is the output:

`rokiatou@rokiatou:~/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build$ make VERBOSE=1`
`/usr/local/bin/cmake -H/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master -B/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build --check-build-system CMakeFiles/Makefile.cmake 0`
/usr/local/bin/cmake -E cmake_progress_start /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build/CMakeFiles /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build'
make -f sycl-gtx/CMakeFiles/sycl-gtx.dir/build.make sycl-gtx/CMakeFiles/sycl-gtx.dir/depend
make[2]: Entering directory `/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build'
cd /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build/sycl-gtx /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build/sycl-gtx/CMakeFiles/sycl-gtx.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build'
make -f sycl-gtx/CMakeFiles/sycl-gtx.dir/build.make sycl-gtx/CMakeFiles/sycl-gtx.dir/build
make[2]: Entering directory `/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build'
[  2%] Building CXX object sycl-gtx/CMakeFiles/sycl-gtx.dir/source/device_selector.cpp.o
cd /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build/sycl-gtx && /usr/bin/c++    -I/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx/sycl-gtx -I/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx/include  -std=gnu++11 -o CMakeFiles/sycl-gtx.dir/source/device_selector.cpp.o -c /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx/source/device_selector.cpp
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx/include/SYCL/device_selector.h:5:0,
                 from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx/source/device_selector.cpp:1:
/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/sycl-gtx/include/SYCL/info.h:6:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.
make[2]: *** [sycl-gtx/CMakeFiles/sycl-gtx.dir/source/device_selector.cpp.o] Error 1
make[2]: Leaving directory `/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build'
make[1]: *** [sycl-gtx/CMakeFiles/sycl-gtx.dir/all] Error 2
make[1]: Leaving directory `/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/sycl-gtx-master/build'
make: *** [all] Error 2

**Comment by ProGTX** [comment]
That is interesting, I don't know how that line is skipped, CMake should fail if it doesn't find OpenCL - which version of CMake are you using? Also, thank you for the detailed output, it makes it much easier for me.

I apologize for not providing any build instructions, I will try to provide them in the near future, but what you did is in theory all that's needed. Unfortunately, I don't have much experience with Nvidia OpenCL on Linux.

A possible workaround for your problem is to provide the OpenCL location to CMake. Adding `-DOpenCL_INCLUDE_DIRS=/usr/local/cuda/` should be enough. Though are you sure this is where the `CL` folder with OpenCL headers is located? The name would imply CUDA, but I don't really know.

Of course, you can just use generic OpenCL headers (https://github.com/KhronosGroup/OpenCL-Headers), which you can most easily obtain by doing `apt-get install opencl-headers`, which will put them into `/usr/include/`.

For the library (`-DOpenCL_LIBRARIES`), it's a bit trickier. I don't want to be too long here, but here is a link which may help you a bit: https://wiki.tiker.net/OpenCLHowTo. But to be honest, I suggest you first try passing only the headers location to CMake and see if it works - there's a possibility your OpenCL library location is already in the path, so the linker would be able to find it.

I hope this helps and please update me on your progress.

**Comment by babouFomb** [comment]
Thanks for your response.

Indeed it is interesting to see that line 13 (`find_package (OpenCL REQUIRED)`) has not just been executed and that cmake did not send an error or warning message.

To solve the problem, it is necessary to remove or comment in CMakelist.txt, the `find_package (OpenCL REQUIRED)` line, and add `find_library (OpenCL_LIBRARIES OpenCL /usr/local/cuda/lib64)` so that make can find the OpenCL library. And giving -DOpenCL_INCLUDE_DIRS=/usr/local/cuda/  commande to cmake help make to find the OpenCL headers.

**Comment by ProGTX** [comment]
I seems like you resolved your problem, thank you for the CUDA feedback. In the meantime, I raised the CMake minimum version to 3.2 (914a1ade75262a6715862e17a9a5ef3824f102c9), which I hope would be better at finding OpenCL.
